baseurl: /university-park
permalink: pretty
markdown: kramdown
paginate: 5
repo: starter
github_org: maptime
maptime:
  chapter: Maptime State College
  twitter: MaptimeSCE
  #disqus: YOUR DISQUS USERNAME
